import type { Metadata } from "next";
import NavBar from "./component/navbar";
import Footer from "./component/footer";
import AllRightReserved from "./component/allright-reserved";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <NavBar />
      {children}
      <Footer />
        <AllRightReserved />
    </div>
  );
}
